#!/usr/bin/env bash

prompt='Screenshot'
mesg="DIR: `xdg-user-dir PICTURES`/Screenshots"

option_1=""
option_2=""
option_3=""
option_4=""
option_5=""


# Rofi CMD
rofi_cmd() {
	rofi -theme-str "window {width: 120px;}" \
		-theme-str "listview {columns: 1; lines: 5;}" \
		-theme-str 'textbox-prompt-colon {str: "";}' \
		-dmenu \
		-p "$prompt" \
		-mesg "$mesg" \
		-markup-rows \
		-theme $HOME/.config/rofi/screenshot/config.rasi
}

run_rofi() {
	echo -e "$option_1\n$option_2\n$option_3\n$option_4\n$option_5" | rofi_cmd
}

# Screenshot
time=`date +%Y-%m-%d-%H-%M-%S`
dir="`xdg-user-dir PICTURES`/Screenshots"
file="Screenshot_${time}.png"

if [[ ! -d "$dir" ]]; then
	mkdir -p "$dir"
fi

notify_view() {
	notify_cmd_shot='dunstify -u low --replace=699'
	${notify_cmd_shot} "Copied to clipboard."
	if [[ -e "$dir/$file" ]]; then
		${notify_cmd_shot} "  Screenshot Saved."
	else
		${notify_cmd_shot} "  Screenshot Deleted."
	fi
}

countdown () {
	for sec in `seq $1 -1 1`; do
		dunstify -t 1000 --replace=699 "  Taking shot in : $sec"
		sleep 1
	done
}


# Copy screenshot to clipboard
copy_shot () {
    xclip -selection clipboard -t image/png < "$file"
}

# take shots
shotnow () {
    cd ${dir} && sleep 0.5 && scrot "$file" && copy_shot
    notify_view
}

shot5 () {
    countdown '5'
    sleep 1 && cd ${dir} && scrot -u "$file" && copy_shot
    notify_view
}

shot10 () {
    countdown '10'
    sleep 1 && cd ${dir} && scrot -u "$file" && copy_shot
    notify_view
}

shotwin () {
    cd ${dir} && scrot -u "$file" && copy_shot
    notify_view
}

shotarea () {
    cd ${dir} && scrot -s -l style=dash,color=blue "$file" && copy_shot
    notify_view
}

run_cmd() {
	if [[ "$1" == '--opt1' ]]; then
		shotnow
	elif [[ "$1" == '--opt2' ]]; then
		shotarea
	elif [[ "$1" == '--opt3' ]]; then
		shotwin
	elif [[ "$1" == '--opt4' ]]; then
		shot5
	elif [[ "$1" == '--opt5' ]]; then
		shot10
	fi
}

# Actions
chosen="$(run_rofi)"
case ${chosen} in
    $option_1)
		run_cmd --opt1
        ;;
    $option_2)
		run_cmd --opt2
        ;;
    $option_3)
		run_cmd --opt3
        ;;
    $option_4)
		run_cmd --opt4
        ;;
    $option_5)
		run_cmd --opt5
        ;;
esac