;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; └────────────────────────────────────────────────────────────┘


[color]
bg = #161616
fg = #FFFFFF
fg-alt = #e12228

transparent = #40000000
launch = #e12228

active_space = #e12228
inactive_space = #b8b8b8
ac = #FEC006

;Cuts
volume_level = #aaaaaa
volume_full = #e12228

;Shapes
shade1 = #3D0608   
shade2 = #5C0A0E
shade3 = #7A0F13
shade4 = #9E141A


;Pacman
mb     = #232323
pacman = #aaaaaa
ghost  = #e12228
points = #aaaaaa
power  = #e12228
pc_cpu = #e12228
pc_ram = #e12228
volume = #e12228
play   = #e12228
play_alt = #e12228