#!/bin/bash

get_vol() {
    # Obtiene volumen en porcentaje del sink por defecto
    volumen=$(pactl get-sink-volume @DEFAULT_SINK@ | awk -F'/' 'NR==1{gsub(/%/,"",$2); print $2}' | tr -d ' ')
    
    # Verifica si está muteado
    mute=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')
    
    if [ "$mute" = "yes" ]; then
        echo "0"
    else
        echo "$volumen"
    fi
}

get_icon() {
    vol=$(get_vol)
    if [ "$vol" = "0" ]; then
        echo "images/mute.png"
    else
        echo "images/volume.png"
    fi
}

case "$1" in
    --vol) get_vol ;;
    --icon) get_icon ;;
    --toggle-muted) pactl set-sink-mute @DEFAULT_SINK@ toggle ;;
esac