;; ┌────────────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀█░█▀▄░█▀▀░█░█░▀█▀░█▀▀░█░█░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█▀▀░█▀▄░█▀▀░▀▄▀░░█░░█▀▀░█▄█░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀░░░▀░▀░▀▀▀░░▀░░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; └────────────────────────────────────────────────────────────────────┘

[global/wm]
margin-bottom = 0
margin-top = 0

include-file = ~/.config/theme/colors/polybar.ini
include-file = ~/.config/polybar/themes/Shapes/glyphs.ini
include-file = ~/.config/polybar/themes/Shapes/modules.ini

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; Bar Settings

[bar/main]
cursor-click = pointer
monitor =
monitor-fallback =
monitor-strict = false
override-redirect = false
bottom = false
fixed-center = true
width = 100%
height = 32
offset-x = 0%
offset-y = 0%
background = ${color.transparent}
foreground = ${color.foreground}
radius-top = 0.0
radius-bottom = 0.0
underline-size = 2
underline-color = ${color.foreground}
border-size = 0
border-color = ${color.transparent}
padding = 0
module-margin-left = 0
module-margin-right = 0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

font-0 = "Iosevka Nerd Font:pixelsize=10;3"
font-1 = "Iosevka Nerd Font:style=Medium:size=22;5"

font-2 = "JetBrainsMono Nerd Font:style=Normal:size=9;3"
font-3 = "JetBrainsMono Nerd Font:style=Medium:size=9;3"
font-4 = "JetBrainsMono Nerd Font:style=Bold:size=9;3"
font-5 = "JetBrainsMono Nerd Font:style=Italic:size=9;3"
font-6 = "JetBrainsMono Nerd Font:style=Medium Italic:size=9;3"
font-7 = "JetBrainsMono Nerd Font:size=19;5"

font-8 = "Feather:size=10.4;3.5"

font-9 = "Material Icons:size=11;4"
font-10 = "Material Icons Outlined:size=11;4"
font-11 = "Material Icons Round:size=11;4"
font-12 = "Material Icons Sharp:size=11;4"
font-13 = "Material Icons TwoTone:size=11;4"

font-14 = "Material Icons:size=15;3.5"

font-15 = "Font Awesome 6 Free Solid:size=10;3"
font-16 = "Material Design Icons Desktop:size=11;3"
font-17 = "Material Design Icons Desktop:size=15;4"

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[bar/top]
inherit = bar/main
offset-y = 0
modules-left = launcher left1 net-info left2 vpn left3 target left4 
modules-center = workspaces
modules-right = right4 battery right3 cpu-info ram-info right2 date right1 sysmenu
enable-ipc = true

[bar/bottom]
inherit = bar/main
offset-y = 0
bottom = true
modules-left = menu left1 filesystem left2 cava left3 left4
modules-center = playerctl
;;modules-center = sep google github reddit gmail twitter
modules-right = right4 settings right3 weather right2 keyboard right1 alsa
enable-ipc = true

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

separator =
dim-value = 1.0
wm-name = 
locale = 
tray-position = none
tray-detached = false
tray-maxsize = 16
tray-background = ${color.transparent}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 0
tray-scale = 1.0
click-left = 
click-middle = 
click-right =
scroll-up =
scroll-down =
double-click-left =
double-click-middle =
double-click-right =
cursor-click = 
cursor-scroll = 

[settings]
throttle-output = 5
throttle-output-for = 10
screenchange-reload = false
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over
pseudo-transparency = false