;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; └────────────────────────────────────────────────────────────┘


[color]
bg = #161616
fg = #FFFFFF
fg-alt = #187bb5

transparent = #40000000
launch = #187bb5

active_space = #187bb5
inactive_space = #b8b8b8
ac = #FEC006


;Cuts
volume_level = #aaaaaa
volume_full = #187bb5


;Shapes
shade1 = #060F1C
shade2 = #0D1F38
shade3 = #14305A
shade4 = #1C4278


;Pacman
mb     = #232323
pacman = #aaaaaa
ghost  = #187bb5
points = #aaaaaa
power  = #187bb5
pc_cpu = #187bb5
pc_ram = #187bb5
volume = #187bb5
play   = #187bb5
play_alt = #aaaaaa