;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; └────────────────────────────────────────────────────────────┘


[color]

# All / Round
bg = #2F343F
fg = #FFFFFF
fg-alt = #7dcfff

transparent = #40000000
launch = #7dcfff

active_space = #7dcfff
inactive_space = #FFFFFF
ac = #FEC006


;Cuts
volume_level = #aaaaaa
volume_full = #7dcfff

;Shapes
shade1 = #2F343F
shade2 = #383E4A
shade3 = #414855
shade4 = #4B5361

;Pacman
mb     = #3A404E
pacman = #e0af68
ghost  = #7dcfff
points = #6D8895
power  = #ffffff
pc_cpu = #9ece6a
pc_ram = #e0af68
volume = #7dcfff
play   = #9ece6a
play_alt = #7dcfff