;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; └────────────────────────────────────────────────────────────┘


[color]
bg = #161616
fg = #FFFFFF
fg-alt = #8ccf7e

transparent = #40000000
launch = #8ccf7e

active_space = #8ccf7e
inactive_space = #b8b8b8
ac = #FEC006


;Cuts
volume_level = #aaaaaa
volume_full = #8ccf7e

;Shapes
shade1 = #021A05
shade2 = #05300A
shade3 = #0A4D12
shade4 = #14b051 

;Pacman
mb     = #232323
pacman = #aaaaaa
ghost  = #8ccf7e
points = #aaaaaa
power  = #8ccf7e
pc_cpu = #8ccf7e
pc_ram = #8ccf7e
volume = #8ccf7e
play   = #8ccf7e
play_alt = #aaaaaa