;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; └────────────────────────────────────────────────────────────┘


[color]
# All / Round
bg = #000000
fg = #ffffff
fg-alt = #ffffff

transparent = #40000000
launch = #ffffff

active_space = #ffffff
inactive_space = #b8b8b8
ac = #FEC006


;Cuts
volume_level = #4d4d4d
volume_full = #ffffff


;Shapes
shade1 = #000000
shade2 = #0A0A0A
shade3 = #131313
shade4 = #1C1C1C

;Pacman
mb     = #0A0A0A
pacman = #ffffff
ghost  = #aaaaaa
points = #aaaaaa
power  = #ffffff
pc_cpu = #ffffff
pc_ram = #ffffff
volume = #ffffff
play   = #aaaaaa
play_alt = #ffffff