#!/bin/sh

. ~/.config/theme/colors/bin.sh

CONFIG="$HOME/.config/theme/config.json"

left=$(jq -r '.bspwmrc.left_padding' "$CONFIG")
right=$(jq -r '.bspwmrc.right_padding' "$CONFIG")
top=$(jq -r '.bspwmrc.top_padding' "$CONFIG")
bottom=$(jq -r '.bspwmrc.bottom_padding' "$CONFIG")
bar=$(jq -r '.bspwmrc.bar' "$CONFIG" | sed "s|~|$HOME|g")

# Java y VMware
wmname LG3D &
vmware-user-suid-wrapper &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

# Padding general
bspc config left_padding   $left
bspc config right_padding  $right
bspc config top_padding    $top
bspc config bottom_padding $bottom

bspc config border_width           '2.5'
bspc config window_gap             '4'
bspc config split_ratio            '1.4'
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config paddingless_monocle    true
bspc config single_monocle         false
bspc config focus_follows_pointer  true

bspc rule -a Gimp       desktop='^8' state=floating follow=on
bspc rule -a Chromium   desktop='^2'
bspc rule -a mplayer2   state=floating
bspc rule -a Kupfer.py  focus=on
bspc rule -a Screenkey  manage=off

bspc config focused_border_color "$focused_border"
bspc config normal_border_color "$normal_border"

feh --bg-fill ~/.Wallpaper/AppliedWallpaper.png

"$bar" &
picom &

if ! pgrep -x dunst > /dev/null; then
    dunst &
fi

# Cursor
xsetroot -cursor_name left_ptr &