;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; └────────────────────────────────────────────────────────────┘

[color]
bg = #ffffff
fg = #000000
fg-alt = #e12228

transparent = #40000000
launch = #e12228

active_space = #e12228
inactive_space = #000000
ac = #FEC006

;Cuts
volume_level = #aaaaaa
volume_full = #e12228

;Shapes
shade1 = #FFFFFF
shade2 = #F5F5F5
shade3 = #EBEBEB
shade4 = #E0E0E0


;Pacman
mb     = #e6e6e6
pacman = #aaaaaa
ghost  = #e12228
points = #000000
power  = #e12228
pc_cpu = #e12228
pc_ram = #e12228
volume = #e12228
play   = #e12228
play_alt = #e12228