; ____       _       _
;|  _ \ ___ | |_   _| |__   __ _ _ __
;| |_) / _ \| | | | | '_ \ / _` | '__|  
;|  __/ (_) | | |_| | |_) | (_| | |     
;|_|   \___/|_|\__, |_.__/ \__,_|_|     
;               |___/

[global/wm]

margin-bottom = 0
margin-top = 0

include-file = ~/.config/theme/colors/polybar.ini
include-file = modules.ini

[bar/top]
monitor = ${env:MONITOR:}
monitor-strict = false
override-redirect = false

bottom = false
fixed-center = true

width = 99.2%
height = 26

offset-x = 0.5%
offset-y = 8

background = ${color.bg}
foreground = ${color.fg}

radius = 4.0

line-size = 2
line-color = ${color.fg-alt}

border-size = 8px
border-color = ${color.bg}

padding = 1

module-margin-left = 0
module-margin-right = 0

; Text
font-0 = "JetBrainsMono:style=Bold:pixelsize=9;3"
; Icons
font-1 = "Font Awesome 6 Free Solid:size=10;3"
font-2 = "Material Design Icons Desktop:size=11;3"
font-3 = "Material Design Icons Desktop:size=15;4"
; Glyphs
font-4 = "MesloLGS NF:style=Regular:pixelsize=17;4"
;dpi = 96

font-5 = "Iosevka Nerd Font:size=13;3"
font-6 = "Iosevka Nerd Font:bold:size=24;2"
font-7 = "Iosevka Nerd Font:size=22;6"
font-8 = "Source Code Pro:size=10;3"
font-9 = "Helvetica Rounded:style=Bold:size=10.5;3"
font-10 = "Montserrat Medium:style=Medium:size=12;3"
font-11 = "Hurmit Nerd Font Mono:style=medium:pixelsize=17;3"


; Text Fonts
font-12 = Iosevka Nerd Font:style=Medium:size=10;4
; Icons Fonts
font-13 = feather:style=Medium:size=12;3
; Powerline Glyphs
font-14 = Iosevka Nerd Font:style=Medium:size=19;3
; Larger font size for bar fill icons
font-15 = Iosevka Nerd Font:style=Medium:size=12;4
; Smaller font size for shorter spaces
font-16 = Iosevka Nerd Font:style=Medium:size=7;4
;iconos bordes redondos
font-17 = "Hurmit Nerd Font Mono:style=Bold:pixelsize=15;3"

modules-left = launcher dots bi net-info bd sep bi prev play next bd sep playerctl sep vpn
modules-center = bi bspwm bd
modules-right = target sep sep bi cpu-info ram-info bd sep bi battery sp pulseaudio bd sep bi date bd sep sep power

separator =
dim-value = 1.0

;wm-restack = bspwm
enable-ipc = true

cursor-click = pointer
cursor-scroll =

[settings]

screenchange-reload = false

compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over

pseudo-transparency = false
