;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; └────────────────────────────────────────────────────────────┘


[color]
bg = #120707
fg = #968c8c
fg-alt = #292929

transparent = #40000000
launch = #292929

active_space = #292929
inactive_space = #968c8c
ac = #FEC006


;Cuts
volume_level = #968c8c
volume_full = #292929

;Shapes
shade1 = #120707
shade2 = #160B0B
shade3 = #201515
shade4 = #291F1F

;Pacman
mb = #201515
pacman = #e0af68
ghost = #292929
points = #292929
power = #292929

pc_cpu = #292929
pc_ram = #292929
volume = #292929
play   = #292929
play_alt = #292929

