;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█▀█░█▀▀░▀█▀░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░█░█▀▀░░█░░█░█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀░▀░▀░░░▀▀▀░▀▀▀│
;; └────────────────────────────────────────────────────────────┘

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; Global WM Settings

[global/wm]
margin-bottom = 0
margin-top = 0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; File Inclusion
include-file = ~/.config/theme/colors/polybar.ini
include-file = ~/.config/polybar/themes/Cuts/modules.ini

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; Bar Settings
[bar]
fill = ﭳ 
empty = ﭳ
indicator = 
width = 6
cursor-click = pointer
format = %{T4}%fill%%indicator%%empty%%{F-}%{T-}

[bar/main]
monitor =
monitor-fallback =
monitor-strict = false
override-redirect = false
bottom = false
fixed-center = true
width = 100%
height = 28
offset-x = 0%
offset-y = 0%
background = ${color.transparent}
foreground = ${color.fg}
radius-top = 0.0
radius-bottom = 0.0
line-size = 2
line-color = ${color.fg-alt}
border-size = 0
border-color = ${color.fg-alt}
padding = 0
module-margin-left = 0
module-margin-right = 0

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;
;;    __________  _   _____________
;;   / ____/ __ \/ | / /_  __/ ___/
;;  / /_  / / / /  |/ / / /  \__ \ 
;; / __/ / /_/ / /|  / / /  ___/ / 
;;/_/    \____/_/ |_/ /_/  /____/ 

font-0 = Iosevka Nerd Font:style=Medium:size=10;4
font-1 = feather:style=Medium:size=12;3
font-2 = Iosevka Nerd Font:style=Medium:size=19;3
font-3 = Iosevka Nerd Font:style=Medium:size=12;4
font-4 = Iosevka Nerd Font:style=Medium:size=7;4

font-5 = "JetBrainsMono Nerd Font:size=19;5"
font-6 = "Feather:size=10.4;3.5"

font-7 = "Material Icons:size=11;4"
font-8 = "Material Icons Outlined:size=11;4"
font-9 = "Material Icons Round:size=11;4"
font-10 = "Material Icons Sharp:size=11;4"
font-11 = "Material Icons TwoTone:size=11;4"

font-12 = "Material Icons:size=15;3.5"

font-13 = "Font Awesome 6 Free Solid:size=10;3"
font-14 = "Material Design Icons Desktop:size=11;3"
font-15 = "Material Design Icons Desktop:size=15;4"

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[bar/top]
inherit = bar/main
cursor-click = pointer
modules-left = launcher workspaces decor1 decor2  net-info decor1 decor2 vpn decor1
modules-right = decor4 target decor3 decor4 cpu-info ram-info decor3 decor4 sp battery volume date sysmenu
enable-ipc = true

[bar/bottom]  
inherit = bar/main
bottom = true
;;modules-left = playerctl prev play next decor3
modules-left = playerctl sp cava decor3
modules-right = decor2 weather sp filesystem
enable-ipc = true

separator =
dim-value = 1.0
wm-name = 
locale = 
tray-position = none
tray-detached = false
tray-maxsize = 16
tray-background = ${color.transparent}
tray-offset-x = 0
tray-offset-y = 0
tray-padding = 0
tray-scale = 1.0

click-left = 
click-middle = 
click-right =
scroll-up =
scroll-down =
double-click-left =
double-click-middle =
double-click-right =

cursor-click = 
cursor-scroll = 

[settings]
throttle-output = 5
throttle-output-for = 10
screenchange-reload = false
compositing-background = source
compositing-foreground = over
compositing-overline = over
compositing-underline = over
compositing-border = over
pseudo-transparency = false