;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;
;;	    ____        __      __              
;;	   / __ \____  / /_  __/ /_  ____ ______
;;	  / /_/ / __ \/ / / / / __ \/ __ `/ ___/
;;	 / ____/ /_/ / / /_/ / /_/ / /_/ / /    
;;	/_/    \____/_/\__, /_.___/\__,_/_/     
;;	              /____/                    
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; Global WM Settings

[global/wm]
margin-bottom = 0
margin-top = 0

include-file = ~/.config/theme/colors/polybar.ini

;; Bar Settings
[bar/main]
monitor =
monitor-fallback =
monitor-strict = false
fixed-center = true
width = 20%
height = 30
offset-x = 20
offset-y = 20
background = ${color.bg}
foreground = ${color.fg}
radius = 10
line-size = 2
line-color = ${color.ac}
border-size = 0
border-color = ${color.bg}
padding = 2
module-margin-left = 1
module-margin-right = 1

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;
;;    __________  _   _____________
;;   / ____/ __ \/ | / /_  __/ ___/
;;  / /_  / / / /  |/ / / /  \__ \ 
;; / __/ / /_/ / /|  / / /  ___/ / 
;;/_/    \____/_/ |_/ /_/  /____/  
                                 
font-0 = "Iosevka Nerd Font:size=18;5"
font-1 = "Iosevka Nerd Font:size=12;2"
font-2 = "Iosevka Nerd Font:bold:size=24;2"
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;
;;    ____  ___    ____      
;;   / __ )/   |  / __ \_____
;;  / __  / /| | / /_/ / ___/
;; / /_/ / ___ |/ _, _(__  ) 
;;/_____/_/  |_/_/ |_/____/  
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_  

[bar/primary]
inherit = bar/main

override-redirect = true
;wm-restack = bspwm
offset-x = 40.20%
offset-y = 15
bottom = false
padding = 1
module-margin-left = 0
module-margin-right = 0
cursor-click = pointer
modules-center = workspaces

;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_
;;
;;	    __  ___          __      __         
;;	   /  |/  /___  ____/ /_  __/ /__  _____
;;	  / /|_/ / __ \/ __  / / / / / _ \/ ___/
;;	 / /  / / /_/ / /_/ / /_/ / /  __(__  ) 
;;	/_/  /_/\____/\__,_/\__,_/_/\___/____/  
;;
;; _-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_-_

[module/workspaces]
type = internal/xworkspaces

pin-workspaces = true
enable-click = true
enable-scroll = true
font-0 = Material Icons:style=Regular
font-1 = FontAwesome5Free:style=Solid:pixelsize=10:antialias=false;3
font-2 = FontAwesome5Brands:style=Solid:pixelsize=10:antialias=false;3
;icon-0 = 1;
icon-0 = 1;-
icon-1 = 2;
icon-2 = 3;
icon-3 = 4;
icon-4 = 5;
;icon-default = 
;icon-default = ─
icon-default = ∙
format = <label-state>
format-padding = 0

;label-active = "  "
;label-active = " "
label-active = " ◉ "
label-active-foreground = ${color.active_space}
label-active-background = ${color.bg}

label-occupied = " ○ "
label-occupied-foreground = ${color.active_space}
label-occupied-background = ${color.bg}

label-urgent = "%icon% "
label-urgent-foreground = ${color.ac}
label-urgent-background = ${color.bg}

label-empty = " ○ "
label-empty-foreground = ${color.inactive_space}
label-empty-background = ${color.bg}