;; ┌────────────────────────────────────────────────────────────┐
;; │░█▀█░█▀█░█░░░█░█░█▀▄░█▀█░█▀▄░░░░░░░░░█▀▀░█▀█░█░░░█▀█░█▀▄░█▀▀│
;; │░█▀▀░█░█░█░░░░█░░█▀▄░█▀█░█▀▄░░░░▀░░░░█░░░█░█░█░░░█░█░█▀▄░▀▀█│
;; │░▀░░░▀▀▀░▀▀▀░░▀░░▀▀░░▀░▀░▀░▀░░░░▀░░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀░▀▀▀│
;; └────────────────────────────────────────────────────────────┘


[color]

# All / Round
bg = #1A1B26
fg = #FFFFFF
fg-alt = #9066dc

transparent = #40000000
launch = #0A9CF5

active_space = #9066dc
inactive_space = #FFFFFF
ac = #FEC006

;Cuts
volume_level = #aaaaaa
volume_full = #9066dc

;Shapes
shade1 = #1A1B26   
shade2 = #252637
shade3 = #33344E
shade4 = #444368

;Pacman
mb     = #222330
pacman = #e0af68
ghost  = #7dcfff
points = #6D8895
power  = #f7768e
pc_cpu = #f7768e
pc_ram = #e0af68
volume = #6b77ad
play   = #9ece6a
play_alt = #0A9CF5